name: Scheduled Deployment

on:
  schedule:
    # 30분마다 실행 (cron 표현식: 분 시 일 월 요일)
    - cron: '*/30 * * * *'

  # 수동 트리거도 추가
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Vercel Deployment
        run: |
          curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_7WrvN7YyOLWorFuaGsxwsRJ7IHk2/1C1Xj6NjRN"